name: Build Android APK (with tun2socks)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"

      # --- Build tun2socks (arm64) ---
      - name: Build tun2socks for android/arm64
        shell: bash
        run: |
          set -eux
          mkdir -p build/bin
          git clone --depth=1 https://github.com/xjasonlyu/tun2socks.git
          cd tun2socks
          export GOOS=android GOARCH=arm64 CGO_ENABLED=0 GO111MODULE=on
          # نکته مهم: مسیر صحیح cmd همین tun2socks است (نه cli)
          go build -trimpath -ldflags='-s -w' -o ../build/bin/tun2socks ./cmd/tun2socks
          cd ..
          # کپی به assets پروژه اندروید
          mkdir -p app/src/main/assets/bin
          cp build/bin/tun2socks app/src/main/assets/bin/tun2socks-arm64
          chmod +x app/src/main/assets/bin/tun2socks-arm64

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug --stacktrace

      - name: Show APK path(s)
        run: ls -alh app/build/outputs/apk/debug || true

      - name: Upload APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
