name: Build Android VPN (with tun2socks + Xray)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      # ---------- Build tun2socks (android/arm64) ----------
      - name: Build tun2socks for android/arm64
        shell: bash
        run: |
          set -eux
          mkdir -p build/bin third_party
          git clone --depth=1 https://github.com/xjasonlyu/tun2socks.git third_party/tun2socks
          pushd third_party/tun2socks
          export GOOS=android GOARCH=arm64 CGO_ENABLED=0 GO111MODULE=on
          # خروجی: build/bin/tun2socks
          go build -trimpath -ldflags="-s -w" -o ../../build/bin/tun2socks ./cmd/cli
          popd

      # ---------- Build Xray-core (android/arm64) ----------
      - name: Build Xray-core for android/arm64
        shell: bash
        run: |
          set -eux
          mkdir -p build/bin third_party
          git clone --depth=1 https://github.com/XTLS/Xray-core.git third_party/xray-core
          pushd third_party/xray-core
          export GOOS=android GOARCH=arm64 CGO_ENABLED=0 GO111MODULE=on
          # خروجی: build/bin/xray
          go build -trimpath -ldflags="-s -w" -o ../../build/bin/xray ./main
          popd

      # ---------- Copy binaries into app assets ----------
      - name: Place binaries into app assets
        shell: bash
        run: |
          set -eux
          mkdir -p app/src/main/assets/bin
          cp -f build/bin/tun2socks app/src/main/assets/bin/
          cp -f build/bin/xray       app/src/main/assets/bin/

      # ---------- Generate Gradle Wrapper (if not in repo) ----------
      - name: Gradle wrapper
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: wrapper

      # ---------- Build APK ----------
      - name: Build Debug APK
        run: ./gradlew --no-daemon :app:assembleDebug

      - name: Show APK path(s)
        run: ls -al app/build/outputs/apk/debug || true

      - name: Upload APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
