name: build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      # ---------- build tun2socks (ARM64 / Android) ----------
      - name: Build tun2socks for android/arm64
        shell: bash
        run: |
          set -eux
          mkdir -p build/bin third_party
          git clone --depth=1 https://github.com/xjasonlyu/tun2socks.git third_party/tun2socks
          pushd third_party/tun2socks
          export GOOS=android GOARCH=arm64 CGO_ENABLED=0 GO111MODULE=on
          # نقطه به‌جای ./cmd/tun2socks  ←  فیکس اصلی
          go build -trimpath -ldflags="-s -w" -o ../../build/bin/tun2socks .
          popd

      # ---------- build xray-core (اختیاری ولی توصیه می‌شود) ----------
      - name: Build Xray-core for android/arm64
        shell: bash
        run: |
          set -eux
          git clone --depth=1 https://github.com/XTLS/Xray-core.git third_party/xray-core
          pushd third_party/xray-core
          export GOOS=android GOARCH=arm64 CGO_ENABLED=0 GO111MODULE=on
          go build -trimpath -ldflags="-s -w" -o ../../build/bin/xray ./main
          popd

      # ---------- کپی باینری‌ها داخل assets اپ ----------
      - name: Place binaries into app assets
        shell: bash
        run: |
          set -eux
          mkdir -p app/src/main/assets/bin/arm64-v8a
          cp -f build/bin/* app/src/main/assets/bin/arm64-v8a/
          chmod +x app/src/main/assets/bin/arm64-v8a/*

      # ---------- نصب Android SDK ----------
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: "34.0.0"

      # ---------- بیلد APK با گرادل ----------
      - name: Build Debug APK
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: assembleDebug

      # ---------- نمایش مسیر APK ----------
      - name: Show APK path(s)
        shell: bash
        run: ls -lah app/build/outputs/apk/debug || true

      # ---------- آپلود خروجی‌ها ----------
      - name: Upload APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
