name: Android CI (build tun2socks + APK)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      # === Build tun2socks (android/arm64) از ریپوی xjasonlyu، فایل main.go در ریشه است ===
      - name: Build tun2socks for android/arm64
        shell: bash
        run: |
          set -eux
          mkdir -p build/bin
          git clone --depth=1 https://github.com/xjasonlyu/tun2socks.git
          pushd tun2socks
          export GOOS=android GOARCH=arm64 CGO_ENABLED=0 GO111MODULE=on
          go build -trimpath -ldflags='-s -w' -o ../build/bin/tun2socks
          popd
          # باینری را داخل assets قرار می‌دهیم تا داخل APK بسته‌بندی شود
          install -Dm755 build/bin/tun2socks app/src/main/assets/bin/tun2socks-arm64

      # اگر gradlew موجود نبود، تولیدش کن (احتیاطی)
      - name: Generate Gradle Wrapper (if missing)
        if: ${{ !exists('gradlew') }}
        shell: bash
        run: |
          set -eux
          mkdir -p gradle/wrapper
          cat > gradle/wrapper/gradle-wrapper.properties <<'EOF'
          distributionBase=GRADLE_USER_HOME
          distributionPath=wrapper/dists
          distributionUrl=https\://services.gradle.org/distributions/gradle-8.7-bin.zip
          zipStoreBase=GRADLE_USER_HOME
          zipStorePath=wrapper/dists
          EOF
          curl -sL https://raw.githubusercontent.com/gradle/gradle/master/gradle/wrapper/gradle-wrapper.jar -o gradle/wrapper/gradle-wrapper.jar
          cat > gradlew <<'EOF'
          #!/usr/bin/env sh
          DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
          exec java -Xmx64m -Xms64m -jar "$DIR/gradle/wrapper/gradle-wrapper.jar" "$@"
          EOF
          chmod +x gradlew

      - name: Make gradlew executable
        run: chmod +x gradlew

      # بیلد APK
      - name: Build Debug APK
        uses: gradle/gradle-build-action@v3
        with:
          arguments: :app:assembleDebug

      - name: Show APK path(s)
        shell: bash
        run: |
          echo "APK files under app/build/outputs:"
          ls -lah app/build/outputs || true
          find app/build/outputs -type f -name "*.apk" -maxdepth 4 -print

      - name: Upload APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/**/*.apk
